### ISSUE TITLE
Add versioning, tagging, docker push

### ISSUE THREAD

**Issue by lrettig** [spacemeshos/poet-ref#106]
We ran into an issue today where after #105 was merged, go-spacemesh system tests started failing because they don't pin the poet version (see https://github.com/spacemeshos/go-spacemesh/pull/2189). In order to facilitate pinning, we should add versioning here and set up automatic dockerbuild/push when a new version is merged or a new release is cut.

**Comment by poszu** [comment]
Closing as already implemented.
