### ISSUE TITLE
evaluate sha256 implementation that is using avx512 instructions

### ISSUE THREAD

**Issue by dshulyak** [spacemeshos/poet-ref#162]
see https://github.com/minio/sha256-simd#support-for-avx512

if poet will be significantly slower than the fastest implementation it will be a security hole

**Comment by pigmej** [comment]
@dshulyak we're already using hw acceleration. AVX512 / AVX2 would be only faster if we could send many hashes at the same time. And then receiving results also in batches. That's not possible in merkle-tree use case.

Our current implementation heavily uses SHA-256 HW extensions and is basically assembly code.
