### ISSUE TITLE
Faulty optimization in PoET verification

### ISSUE THREAD

**Issue by zalmen** [spacemeshos/poet-ref#38]
In `verifier.Verify`, the optimization that marks the proof as valid if we already handled one of the siblings on the way to the root is wrong. The fact that we got to a known sibling says nothing on the validity of the path that we already calculated (i.e. from the leaf to the current position). A correct optimization will require storing in the cache sibling pairs (instead of only one of them) and if we got to a pair we can indeed stop the verification and mark the proof as valid.

**Comment by moshababo** [comment]
#37 should fix this.
