### ISSUE TITLE
Integration with node broken

### ISSUE THREAD

**Issue by y0sher** [spacemeshos/poet-ref#70]
Recent updates #66 and #67 broken integration with the `go-spacemesh` node. please check the node and run tests before or atleast after merging changes.

Those changes break all integration in a way that go-spacemesh cannot be tested right now.

**Comment by avive** [comment]
@moshababo - is still still an issue? How can any go-spacemesh changes be tested if this issue is not fixed? @y0sher ?

**Comment by lrettig** [comment]
We should add tests to CI that make sure changes to POET don't break integration - shouldn't be too hard to add a test that checks out latest go-spacemesh and tests the two together.
