### ISSUE TITLE
Open round recovery policy

### ISSUE THREAD

**Issue by moshababo** [spacemeshos/poet-ref#79]
### Background

* PoET Service starts with the opening of round 1 (opening duration is specified by the `initialduration` mandatory flag).
* Once duration elapsed, round 1 starts executing, and round 2 is opening.
* Round 2 start of execution (and round 3 opening) is defined by rounds scheduling (`duration` optional flag). If it happens before round 1 end of execution, there would be 2 rounds executing in-parallel. If after, there would be a period in which no round would be executing. Current behaviour is to start round 2 execution on round 1 end of execution if scheduling time is after or not defined (so there's always at least 1 execution).

#### Options for when attempting to recover a round in “open” state (after server crash or shutdown):

1. Execute it immediately and open a new round instead.
2. Keep it open until the previous round end of execution, regardless of the opening schedule.
3. If schedule is/was defined, keep it open for the remaining duration, including the duration in which the server was down. If elapsed, execute it immediately.
4. If schedule is/was defined, keep it open for the remaining duration, _not_ including the duration in which the server was down. This might create a time drift in the overall scheduling.

Option 1 is currently implemented. This creates an issue of creating an additional parallel round execution for every server restart attempt, and thus should be changed.

Main consideration is to whether we plan to use the rounds scheduling or just start executing each round on the previous round end of execution. If the first, options 2-4 are viable. If the later, option 2 is the fallback and need to be implemented anyway. 

Please provide feedback for the desired behaviour.

**Comment by noamnelke** [comment]
I suggest changing the way it works a little. Instead of `initialduration` we pass a `genesis_time`, and the initial round is open until that time and then starts executing.

Same as today, we pass an optional `round_duration` param.

### If `round_duration` was omitted
There's always one round open and exactly one executing. When we recover, the first round resumes execution and the second re-opens.

### If `round_duration` was provided
Starting from `genesis_time`, a round starts every `round_duration`, regardless of current execution.

This means there could be 0-∞ executing rounds. It also means that at recovery time we can calculate which round is supposed to be open and all lower rounds should be executing.

**Comment by moshababo** [comment]
* `genesis_time` over `initialduration` just means absolute time instead of relative duration? 
* if round duration is specified, then what you described is option 3, and if not, option 2. correct?

**Comment by noamnelke** [comment]
- Yes, absolute instead of relative to when the command was executed.
- I don't understand how option 3 can be implemented if you don't have the absolute time... But otherwise, yes.

**Comment by noamnelke** [comment]
To be even more precise and specific: I think that `genesis_time` should be the same as what the nodes receive and `round_duration` should be the length of an epoch. I think we should also provide an additional param called `genesis_offset` or `epoch_offset` that is a duration to be added to the `genesis_time` param. This will make it easy to configure a set of PoET servers with different offsets and the same `genesis_time`.

I believe that the duration will have enough of a buffer in it, that it will be unlikely that there will ever be 2 concurrent rounds and I think we'll always provide a duration, so perhaps we can avoid implementing option 2.

**Comment by moshababo** [comment]
> I don't understand how option 3 can be implemented if you don't have the absolute time... But otherwise, yes.

The actual absolute time in which the round opening started can be saved to disk. So it can be calculated from the round state, not the params.

> To be even more precise and specific: I think that genesis_time should be the same as what the nodes receive and round_duration should be the length of an epoch. I think we should also provide an additional param called genesis_offset or epoch_offset that is a duration to be added to the genesis_time param. This will make it easy to configure a set of PoET servers with different offsets and the same genesis_time.

Nice idea

> I believe that the duration will have enough of a buffer in it, that it will be unlikely that there will ever be 2 concurrent rounds

If we'll have enough buffer, it means that there would be periods in which no round would be executed. Is this acceptable?

> I think we'll always provide a duration, so perhaps we can avoid implementing option 2.

We need to decide whether we want to support a mode in which `round_duration` is omitted, or not.

**Comment by noamnelke** [comment]
> If we'll have enough buffer, it means that there would be periods in which no round would be executed. Is this acceptable?

It's not ideal. Ideally we'd have PoETs work more or less back-to-back with minimal time between. This would allow us to make full use of the resources we pay for (or close to it). However, at first I imagine we'll do that to increase predictability.

Having 2 concurrent rounds in the same process sounds like a bad idea to me anyway. When we reduce the buffer, if a round is delayed, we'll probably prefer to finish it ASAP and start the next round with a slight delay than work on both in parallel.

> We need to decide whether we want to support a mode in which `round_duration` is omitted, or not.

At first I thought we'd want that, but I can't really justify it, so I vote to drop support.

**Comment by barakshani** [comment]
Should we make sure that there is no time race between closing registration/starting executing and opening a new round (I understand that it is milliseconds)?
I suggest to have an overlap between round j and j+1, such that registration for round j+1 starts before the registration to round j is actually closed.
If in the future we would shift to on-chain registration (practically it means that we gossip registration requests), I think that the suggestion above would be even more desired.

We should consider having rounds totally independent from one other. It means that a round should start at a given time, instead of waiting for the previous execution to finish.

For `initialduration` we should also consider the full Genesis flow (which is not completed at the moment).

**Comment by noamnelke** [comment]
The round switching is well implemented at the moment. Any registration will either be included in round `j` or round `j+1` and never get lost.

> We should consider having rounds totally independent from one other. It means that a round should start at a given time, instead of waiting for the previous execution to finish.

The problem with this is that if there was a delay for some reason (e.g. server fault) that causes the first round to spill into the second, and we start computing them in parallel, the first round completion will be even more delayed than if we focused our CPU core only on that round.

There's also nothing to gain from that, as the second round will complete at the same time it would if we started it when the first round completes.

I think it's best to try to avoid this situation as much as possible, but if it does happen, only work on one round at a time on a single process/core.

> For `initialduration` we should also consider the full Genesis flow (which is not completed at the moment).

I agree, but I believe that what I described will work well with what we'll end up doing, if I have my way 😉

**Comment by noamnelke** [comment]
Example:

Let's say your CPU core can perform 100 hashes per minute.

At the time the second round should begin you still need to perform 1,000 hashes on the first round. You could finish it in 10 minutes and start (and therefore finish) the second round 10 minutes late.

If you work on them in parallel, and you split your available hashes evenly, you'll finish the first round 20 minutes late and in those 20 minutes, you've advanced the second round exactly 1,000 hashes instead of 2,000, so it'll still be 10 minutes late.

**Comment by noamnelke** [comment]
We should have a small buffer, so that in such a case it will _eventually_ re-align, but being a little late is fine, as long as `X` is large enough.

**Comment by moshababo** [comment]
I don't think you can view the machine as a "pool" of hashes per min. The machine will usually be underutilized CPU-wise with 1 round execution only, in addition to having synchronization bottlenecks like disk writes or channel ops (if we'll make the disk writes async), which reduce the overall CPU utilization. We can easily benchmark the parallel execution behaviour if it's important for us.

My overall conclusion is that we're not baked to fully plan the rounds scheduling, in addition to having a roadmap of optimizations which will allow greater flexibility in the future. So my suggestion is to keep supporting both modes (rounds can be independent of each other, or not), and implement options 2 & 3 for the open round recovery.

Any objections?

**Comment by moshababo** [comment]
I don't think you can view the machine as a "pool" of hashes per min. The machine will usually be underutilized CPU-wise with 1 round execution only, in addition to having synchronization bottlenecks like disk writes or channel ops (if we'll make the disk writes async), which also reduce the overall CPU utilization. We can easily benchmark the parallel execution behaviour if it's important for us.

My overall conclusion is that we're not baked to fully plan the rounds scheduling, in addition to having a roadmap of optimizations which will allow greater flexibility in the future. So my suggestion is to keep supporting both modes (rounds can be independent of each other, or not), and implement options 2 & 3 for the open round recovery.

Any objections?

**Comment by noamnelke** [comment]
I thought we're moving towards running a separate process on each CPU core. That was my basic assumption.

**Comment by barakshani** [comment]
To emphasise @noamnelke's point: once we have sufficiently many poets, we would like to have each working back to back.
If epoch is 24 hours, then each poet should run for, say, 23 hours. A miner would get the proof from poet A (which will then start a new round immediately), will generate a post proof and publish her ATX -- within one hour -- then the miner will register to poet B that starts execution before hour 24 ends.
That why the miner will always be synced for a 24-hour epochs: 23 hours of waiting for the proof, and one hour to publish ATX and register to the following round.

**Comment by poszu** [comment]
@moshababo, @noamnelke I think that ideas from this discussion have been implemented plus it's quite old so I'm closing.
