### ISSUE TITLE
Document usage

### ISSUE THREAD

**Issue by lrettig** [spacemeshos/poet-ref#90]
There's currently no documentation on how to run the POET server. Add at least a basic "# Running the server" section to the README. It should contain instructions on how to connect go-spacemesh to it.

Happy to work on this.

@moshababo, does anything special need to be done? When I run poet locally, I noticed that it's looking for a `poet.conf`. Can we add a sample of this to the repo? Do I need to supply any commandline args? Or should go-spacemesh connect to it (on the default port) with no special params/config required?

**Comment by moshababo** [comment]
@lrettig sorry for the delay. This was addressed by https://github.com/spacemeshos/poet/pull/95. Please verify.

**Comment by lrettig** [comment]
Looks good! I was able to build and run a poet server locally using the updated README. Thanks!
